# Generated by Django 4.2.1 on 2023-06-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=100)),
                ('mobile', models.IntegerField()),
                ('email', models.TextField(default='DEFAULT VALUE', max_length=100)),
                ('social_number', models.IntegerField()),
                ('address', models.TextField(max_length=255)),
                ('contact_1', models.TextField(max_length=100)),
                ('contact_1_mobile', models.IntegerField()),
                ('contact_2', models.TextField(max_length=100)),
                ('contact_2_mobile', models.IntegerField()),
                ('birth_date', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'Feminino'), ('O', 'Outro'), ('N', 'nao_informar')], default='N', max_length=1)),
            ],
        ),
    ]
