# Generated by Django 4.2.1 on 2023-06-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_client_contact_1_mobile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact_1_mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='contact_2_mobile',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
