# Generated by Django 4.2.1 on 2023-06-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_client_contact_1_mobile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_1',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_1_mobile',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_2',
        ),
        migrations.RemoveField(
            model_name='client',
            name='contact_2_mobile',
        ),
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.IntegerField(null=True),
        ),
    ]
