# Generated by Django 4.2.1 on 2023-06-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_remove_client_contact_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
