# Generated by Django 4.2.1 on 2023-06-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('responsible_guide', models.TextField(max_length=60)),
                ('departure_destination', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('type', models.TextField(default='DEFAULT VALUE', max_length=30)),
                ('vehicle_plate', models.TextField(max_length=10)),
                ('date_departure', models.DateField(blank=True, null=True)),
                ('date_arrival', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
