# Generated by Django 4.2.1 on 2023-06-28 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Travel',
        ),
    ]
