# Generated by Django 4.2.1 on 2023-07-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('travels', '0002_rename_client_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_sender', models.IntegerField()),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('average_value', models.TextField(default='DEFAULT VALUE', max_length=30)),
                ('approximate_weight', models.TextField(max_length=10)),
                ('approximate_size', models.DateField(blank=True, null=True)),
                ('recipient_data', models.DateField(blank=True, null=True)),
                ('travel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel', to='travels.travel')),
            ],
        ),
    ]
