# Generated by Django 4.2.1 on 2023-07-04 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approximate_size',
            field=models.TextField(max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='average_value',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='recipient_data',
            field=models.TextField(max_length=10),
        ),
    ]
